#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config focused_border_color "#a7c1d0"
bspc config normal_border_color "#0b0f10"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a Steam desktop='^4' state=floating
bspc rule -a firefox desktop='^2'
bspc rule -a firefox:Toolkit sticky=on state=floating
#bspc rule -a mpv sticky=on state=floating
#bspc rule -a Sxiv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
picom &
dunst &
xsetroot -cursor_name left_ptr
